language: node_js
node_js:
  - 12.12
install:
  - npm ci
script:
  - npm run docs:build
deploy:
  provider: master
  skip_cleanup: true
  local_dir: docs/.vuepress/dist
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: dev
